databases:
  - name: carsdb
    databaseName: carsdb
    user: carsdb_user


services:
  - type: web
    name: epic
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: epic
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false